### PR TITLE
Fix building Uzem under MS Windows

### PR DESCRIPTION
**Pull request by danboid**
These changes fix building uzem, and hence the full Uzebox repo, using msys2 under MS Windows.

I have tested that Uzem still builds fine under Linux with these changes.

### CODE REVIEW

**Comment by weber21w** [comment]
Looks good to me, I'd say merge it.

**Comment by danboid** [comment]
If anyone wants to test it, see:

https://uzebox.org/wiki/Windows_Software_Installation#Building_the_Uzebox_repository_using_MSYS2

**Comment by danboid** [comment]
I forgot to mention that I have tested uzem for Windows (Windows 10 in my case) after building it using my repo and the instructions here:

https://uzebox.org/wiki/Windows_Software_Installation#Building_the_Uzebox_repository_using_MSYS2

I have just updated those instructions now to note that the user has to install SDL2.dll if they want to run uzem. You can build Uzem fine under msys2 with only the msys2 SDL2 package installed but without having SDL2.dll installed under c:\windows\system32, that only needs to be in place to run it.

**Comment by artcfox** [comment]
Please do not say to put it in the system folder. That may break other apps
that rely on a different minor version of SDL. Place it next to our exe
like the previous instructions.

**Comment by danboid** [comment]
Yes I can see the sense in that. I have updated the Windows repo install instructions and the CUzebox wiki page to recommend copying sdl2.dll into the same directory instead of c:\windows\system32.

**Comment by danboid** [comment]
Is anything else required before we can merge this?

**Pull request merged**
